use anyhow::Result;
use futures::prelude::*;
use mapreduce::{
    cluster::ClusterConfig,
    map::MapRequest,
    server::{MapReduceServer, MapReduceService, MapReduceServiceClient}, wasm::DefaultWasmEnv,
};
use tarpc::{
    client, context,
    server::{self, Channel},
};

#[tokio::main]
async fn main() -> Result<()> {
    let (client_transport, server_transport) = tarpc::transport::channel::unbounded();

    let server = server::BaseChannel::with_defaults(server_transport);

    let server_instance = MapReduceServer::<DefaultWasmEnv>::new();

    tokio::spawn(
        server
            .execute(server_instance.serve())
            // Handle all requests concurrently.
            .for_each(|response| async move {
                tokio::spawn(response);
            }),
    );

    // WorldClient is generated by the #[tarpc::service] attribute. It has a constructor `new`
    // that takes a config and any Transport as input.
    let config = dbg!(client::Config::default());
    let client = MapReduceServiceClient::new(config, client_transport).spawn();

    // The client has an RPC method for each RPC defined in the annotated trait. It takes the same
    // args as defined, with the addition of a Context, which is always the first arg. The Context
    // specifies a deadline and trace information which can be helpful in debugging requests.

    let context = dbg!(context::current());

    let hello = client
        .map(
            context,
            MapRequest {
                key_range: Vec::new(),
                r: 0,
                map_src: String::from(""),
                partition_src: String::from(""),
                reader_src: String::from(""),
            },
        )
        .await?;

    println!("{:?}", hello);

    Ok(())
}
