use anyhow::Result;
use futures::prelude::*;
use mapreduce::{
    cluster::ClusterList,
    server::{MapReduceServer, MapReduceService},
    wasm::DefaultWasmEnv,
};
use std::{net::{IpAddr, Ipv6Addr}, sync::Arc};
use tarpc::server::{self, Channel, incoming::Incoming};

async fn spawn(fut: impl Future<Output = ()> + Send + 'static) {
    tokio::spawn(fut);
}

#[tokio::main]
async fn main() -> Result<()> {
    let cluster_list = ClusterList::new(vec![("[::1]".to_owned(), 3000)]);
    let server_addr = (IpAddr::V6(Ipv6Addr::LOCALHOST), 3000);

    let mut listener = tarpc::serde_transport::tcp::listen(
        &server_addr,
        tarpc::tokio_serde::formats::Json::default,
    )
    .await?;
    listener.config_mut().max_frame_length(usize::MAX);

    let cluster = Arc::new(cluster_list.connect().await);

    listener
        // Ignore accept errors.
        .filter_map(|r| future::ready(r.ok()))
        .map(server::BaseChannel::with_defaults)
        .max_channels_per_key(2, |t| t.transport().peer_addr().unwrap().ip())
        // serve is generated by the service attribute. It takes as input any type implementing
        // the generated World trait.
        .map(|channel| async {
            let server = MapReduceServer::<DefaultWasmEnv>::new(cluster.clone());
            channel.execute(server.serve()).for_each(spawn).await
        })
        // Max 10 channels.
        .buffer_unordered(10)
        .for_each(|_| async {})
        .await;

    // let (client_transport, server_transport) = tarpc::transport::channel::unbounded();

    // let server = server::BaseChannel::with_defaults(server_transport);

    // let server_instance = MapReduceServer::<DefaultWasmEnv>::new();

    // tokio::spawn(
    //     server
    //         .execute(server_instance.serve())
    //         // Handle all requests concurrently.
    //         .for_each(|response| async move {
    //             tokio::spawn(response);
    //         }),
    // );

    // // WorldClient is generated by the #[tarpc::service] attribute. It has a constructor `new`
    // // that takes a config and any Transport as input.
    // let config = dbg!(client::Config::default());
    // let client = MapReduceServiceClient::new(config, client_transport).spawn();

    // // The client has an RPC method for each RPC defined in the annotated trait. It takes the same
    // // args as defined, with the addition of a Context, which is always the first arg. The Context
    // // specifies a deadline and trace information which can be helpful in debugging requests.

    // let context = dbg!(context::current());

    // client
    //     .map(
    //         context,
    //         MapRequest {
    //             key_range: Vec::new(),
    //             r: 0,
    //             map_src: String::from(""),
    //             partition_src: String::from(""),
    //             reader_src: String::from(""),
    //         },
    //     )
    //     .await?;

    // println!("{:?}", ());

    Ok(())
}
